apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realsight
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: realsight
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/G0rg0ne/RealSight.git
    targetRevision: main
    path: k8s/realsight
  destination:
    server: https://kubernetes.default.svc
    namespace: realsight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
